In [2]:
import numpy as np

In [ ]:
# 2D array

arr2D = np.array([[1,2,3], [4,5,6],[7,8,9] ])
print(arr2D)

print(np.sum(arr2D))        #sum of arr

sum_of_col = np.sum(arr2D, axis=0)
print(sum_of_col)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])      #slice the arr first right the idx of row(0:2) means row 0 and 1 and then col(1:2) means col 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [ ]:
# 3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])        # 2×3×2

print(arr3D, arr3D.shape)
print(arr3D[0,2,1])

print(arr3D[:,0,:])     # access first row from both  layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
6
[[1 2]
 [7 8]]
