In [5]:
import numpy as np

In [6]:
# mathematical functions

# aggregation func
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.max(arr))
print(np.min(arr))

print(np.argmax(arr))   #return idx of max val
print(np.argmin(arr))   #return idx of min val

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))      # return standard deviation
print(np.var(arr))      # return variance(sq of std or sigma sq)

15
120
5
1
4
0
3.0
3.0
1.4142135623730951
2.0


In [8]:
# power func

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [9]:
# log

print(np.log(arr))      # here base is e
print(np.log10(arr))    # here base is 10
print(np.log2(arr))     # here base is 2

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


In [ ]:
# rounding
print(np.round(3.14))
print(np.ceil(3.14))    # round up
print(np.floor(3.14))   # round down
print(np.trunc(3.14))

nums = np.array([1,2,3,1,5,6,3])

print(np.unique(nums))      # give unique val, and does not repeat the same el
print(np.sort(nums))

n = np.array([1,-2,3,-1,-5])
print(np.abs(n))    # converts all the arr el into +ve

3.0
4.0
3.0
3.0
[1 2 3 5 6]
[1 1 2 3 3 5 6]
[1 2 3 1 5]
