In [1]:
import numpy as np

In [11]:
# creating an numpy arr

# 1D arrays
arr1 = np.ones((5,))
print(arr1)

#2D arrays
arr2 = np.zeros((2,3), dtype = "int64")   #prefill
print(arr2)

arr3 = np.full((3,3), 5)    # prefill with values
print(arr3)

arr4 = np.eye(4)     # identity matrix
print(arr4)

arr5 = np.arange(0,11, 2)     # range elements- arange func takes 3 para, strt, end, and step(step can be skip so we don't pass it takes 1 as default). it stores no. strt from end-1
print(arr5)

arr6 = np.linspace(1,100,5)    # evenly spaced arr - take paras - strt,end and in how much part to divide. 
print(arr6)

[1. 1. 1. 1. 1.]
[[0 0 0]
 [0 0 0]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  2  4  6  8 10]
[  1.    25.75  50.5   75.25 100.  ]


In [21]:
# properties

arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

# float_arr = arr.astype(np.float64)
float_arr = arr.astype(float)
print(float_arr)

str_arr = arr.astype(str)
print(str_arr)

(2, 3)
6
int64
2
[[1. 2. 3.]
 [4. 5. 6.]]
[['1' '2' '3']
 ['4' '5' '6']]
