In [1]:
import numpy as np

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)
print(arr[0][2])

# reshaped = arr.reshape((3,2))
# print(arr, arr.shape) 


# flatten_arr = arr.flatten()
# print(flatten_arr) 

[[1 2 3]
 [4 5 6]] (2, 3)
3


In [ ]:
# indexing arr
arr2 = np.array([1,2,3,4,5])
print(arr2[0])

#fancy indexing- 
idx = [0,1,3]
print(arr2[idx])

#boolean indexing
print(arr2[arr2>3]) 
print(arr2[arr2%2==0])

#slicing
print(arr2[1:4])
print(arr2[:4:2])       # here 2 is step 

1
[1 2 4]
[4 5]
[2 4]
[2 3 4]
[1 3]


In [ ]:
# copy and view:-  
nums = [1,2,3,4,5]
sub_list = nums[1:3]     # in py list it creates an copy for slicing method
print(sub_list)
sub_list[0] = 25        # change in sub list does not change actual list

arr = np.array(nums)
sub_arr = arr[1:3]      # in np arr it creates a view of original arr in slicing method
print(sub_arr)

sub_arr[0] = 25     # change in sub arr also affects the original arr as it is does not create any other copy of the arr. that's the reason np arr are fast
print(arr)

#  to create copy we use .copy method

new_arr = arr[1:3].copy()
print(new_arr)

[2, 3]
[2 3]
[ 1 25  3  4  5]
