In [1]:
import numpy as np

In [2]:
# vectorization
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,6,2,])

print(arr1+arr2)

[ 6  6  6 10  7]


In [4]:
# broadcasting
arr = np.array([1,2,3,4,5])
print(arr+5)

# doing operation or broadcasting on two diff arr is only possible when the shape of the has one same shape(or size) and any of one has 1 shape.
# Eg- arrays of 2×3 and 2×5 is not possible but arrays of 2×3 and 2×1 is possible
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr+arr3)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [6]:
# vector normalization 

a = np.array([[1,2],[3,4]])

mean = np.mean(a)
sd = np.std(a)    # standard deviation

normalized_arr = (a-mean)/sd
print(normalized_arr)

print(mean)
print(sd)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
